staticDir:
    - static

assetDir: static

publishDir: generated

disableHugoGeneratorInject: true

outputFormats:
    - html:
        minify:true

minificationOptions:
    KeepConditionalComments: true
    KeepEndTags: false