staticDir:
    - static

assetDir: static

publishDir: generated

disableHugoGeneratorInject: true
#disableLiveReload: true

enableRobotsTXT: true

permalinks:
  posts: /:year/:month/:title/

outputFormats:
    - html:
        minify:true

minificationOptions:
    KeepConditionalComments: true
    KeepEndTags: false
