name: Deployment

on:
  push:
    branches:
      - master
      
jobs:

  deployclouflare:
    name: Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
    -
      name: create deployment
      uses: niklasmerz/github-deployment-action@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: -o ironpeakservices -r ironpeak.be -c master -e production
    -
      name: set deployment success
      uses: niklasmerz/github-deployment-action@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: -o ironpeakservices -r ironpeak.be -s success -u https://ironpeak.be -f
