name: vulnerability scan
on:
  schedule:
  - cron: '0 0 * * *'
steps:
  - name: ZAP Scan
    uses: zaproxy/action-baseline@v0.2.0
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      target: 'https://ironpeak.be/'
